version: 0.2
phases:
  install:
    commands:
       - npm install # run npm install to install all dependencies
       - npm run build
artifacts:
  files:
     - '**/*' #copy all build files to S3 location